#!/bin/bash
mkdir -p 'pack/mitchplugins/start'
cd 'pack/mitchplugins/start'
git clone https://github.com/mitchpaulus/vim-siemens-ppcl.git
git clone https://github.com/mitchpaulus/autocorrect.vim.git
git clone https://github.com/mitchpaulus/vim-tex2text.git
git clone https://github.com/mitchpaulus/latex-plus.git

mkdir -p $HOME/.vim/bundle
cd $HOME/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git
